[tools]
"aqua:opentofu/tofu-ls" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"pipx:zuban" = "latest"
bun = "latest"
claude = "latest"
codex = "latest"
deno = "latest"
go = "latest"
java = "temurin"
lua-language-server = "latest"
neovim = "nightly"
node = "lts"
oxfmt = "latest"
oxlint = "latest"
python = "latest"
ruff = "latest"
stylua = "latest"
usage = "latest"
uv = "latest"
yamlfmt = "latest"
tree-sitter = "latest"
