theme = "onedark"

[editor]
line-number = "relative"
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.statusline]
left = ["mode", "spinner", "file-name", "version-control"]

[keys.insert]
j = { k = "normal_mode" }
k = { j = "normal_mode" }
