[language-server.rust-analyzer]
command = "rustup"
args = ["run", "nightly", "rust-analyzer"]
config = { check = { command = "clippy" } }

[[language]]
name = "rust"
auto-format = true
language-servers = [ "rust-analyzer" ]

[[language]]
name = "c"
auto-format = true
indent = { tab-width = 4, unit = "    " }
