[[language]]
name = "rust"
language-server = { command = "rustup", args = ["run", "nightly", "rust-analyzer"] }
auto-format = false

[[language]]
name = "c"
auto-format = true
indent = { tab-width = 4, unit = "    " }
