[[language]]
name = "rust"
auto-format = true
language-servers = [ "rust-analyzer" ]

[language-server.rust-analyzer]
command = "rustup"
args = ["run", "nightly", "rust-analyzer"]
config = { check = { command = "clippy" } }

[[language]]
name = "c"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "go"
auto-format = true

[[language]]
name = "typescript"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "tsx"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }
