unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Automatic rename
set -g status-interval 2
set -g allow-rename on
set -g automatic-rename on
set -g renumber-windows on
set -g automatic-rename-format '#{b:pane_current_path}'

set -g base-index 1
set -g default-terminal "${TERM}"
set -g focus-events on
set -g mouse on
set -g status on

setw -g mode-keys vi

bind v copy-mode
bind y choose-window "join-pane -v -s "%%"" # Selected pane to current window
bind u choose-window "join-pane -h -s "%%"" # Current pane to selected window
bind b break-pane # Current pane to new window
bind P display-popup -E "tmux -L popup new-session -A -s popup"
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

bind -r C-k resize-pane -U
bind -r C-j resize-pane -D
bind -r C-h resize-pane -L
bind -r C-l resize-pane -R

bind -T copy-mode-vi 'v' send -X begin-selection
bind -T copy-mode-vi 'y' send -X copy-selection-and-cancel
bind -T copy-mode-vi C-j send-keys -X cursor-down \; send-keys -X cursor-down \; send-keys -X cursor-down \; send-keys -X cursor-down \; send-keys -X cursor-down
bind -T copy-mode-vi C-k send-keys -X cursor-up \; send-keys -X cursor-up \; send-keys -X cursor-up \; send-keys -X cursor-up \; send-keys -X cursor-up

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R
bind -n M-z resize-pane -Z
bind -n M-x set-option status

bind -n C-x setw synchronize-panes

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'Morantron/tmux-fingers'

set -g @fingers-key f

bind e run -b "#{@fingers-cli} start #{pane_id} --patterns path --main-action 'xargs tmux new-window nvim'"

# https://github.com/deparr/tairiki.nvim/blob/4699c41536fb83e2dadae436e1eba2435fa64b08/extra/tmux/tairiki.tmux
# TAIRIKI THEME BEGIN
tairiki_fg="#c5c8c6"
tairiki_bg="#151515"
tairiki_gray0="#1D2021"
tairiki_gray1="#696969"
tairiki_gray2="#A89984"
tairiki_gray3="#cccccc"

set-option -g clock-mode-style              24
set-option -g clock-mode-colour             "$tairiki_gray2"

set-option -g status-fg                     "$tairiki_fg"
set-option -g status-bg                     "$tairiki_bg"
set-option -g copy-mode-current-match-style "fg=$tairiki_gray0,bg=$tairiki_gray3"
set-option -g copy-mode-match-style         "fg=$tairiki_gray0,bg=$tairiki_gray3"
set-option -g menu-selected-style           "fg=$tairiki_gray0,bg=$tairiki_fg"
set-option -g menu-style                    "fg=$tairiki_fg,bg=$tairiki_gray0"
set-option -g message-style                 "bg=$tairiki_gray2,fg=$tairiki_gray0"
set-option -g message-command-style         "bg=$tairiki_gray2,fg=$tairiki_gray0"
set-option -g mode-style                    "bg=$tairiki_gray3,fg=$tairiki_gray0"
set-option -g pane-active-border-style      "fg=$tairiki_gray0"
set-option -g pane-border-lines             "heavy"
set-option -g pane-border-style             "fg=$tairiki_gray1"
set-option -g popup-border-lines            "rounded"
set-option -g status-right-style            "fg=$tairiki_gray2"
set-option -g window-status-current-style   "fg=$tairiki_gray3"
set-option -g window-status-style           "fg=$tairiki_gray2"
set-option -g window-style                  "bg=$tairiki_gray0" # Custom inactive bg
set-option -g window-active-style           'bg=terminal' # Custom active bg
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

set-option -g status-right                 ' #{?#{>:#{server_sessions},1},(#{session_name}),} %d/%m #(date +"%H:%M") '
set-option -g status-left                  ' '
# TAIRIKI THEME END

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
