unbind C-b
set -g prefix C-a
bind C-a send-prefix


# Automatic rename
set -g status-interval 2
set -g allow-rename on
set -g automatic-rename on
set -g renumber-windows on
set -g automatic-rename-format '#{b:pane_current_path}'

set -g base-index 1
set -g focus-events on
set -g status on
set -g mouse on
set -g renumber-windows on

setw -g mode-keys vi

set -g window-style 'bg=#1a1a1a'
set -g window-active-style 'bg=terminal'
set -g pane-border-style fg=white
set -g pane-active-border-style fg=blue
set -g status-style fg=terminal,bg=terminal

bind -r C-k resize-pane -U
bind -r C-j resize-pane -D
bind -r C-h resize-pane -L
bind -r C-l resize-pane -R
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

bind -n M-z resize-pane -Z
bind -n M-x set-option status
