"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
email = "ama.thorsrud@gmail.com"
name = "Amandus Søve Thorsrud"

[signing]
behavior = "own"
backend = "gpg"

[ui]
diff-formatter = ":git"
pager = ["delta", "--pager", "less -FRX"]
diff-editor = ["nvim", "-c", "DiffEditor $left $right $output"]
conflict-marker-style = "git"

[[--scope]]
--when.commands = ["diff", "show"]
[--scope.ui]
pager = "delta"
