"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
email = "ama.thorsrud@gmail.com"
name = "Amandus Søve Thorsrud"

[ui]
diff-formatter = "delta"
diff-editor = ["nvim", "-c", "DiffEditor $left $right $output"]
conflict-marker-style = "git"

[merge-tools.delta]
diff-expected-exit-codes = [0, 1]

[signing]
behavior = "own"
backend = "gpg"
