"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
email = "ama.thorsrud@gmail.com"
name = "Amandus Søve Thorsrud"

[signing]
behavior = "drop"
backend = "ssh"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFaRcZKH9CJsX39JG5MHnw0HFnpm/0ugJdWP95+F4Cp8"

[git]
sign-on-push = true

[ui]
diff-formatter = ["difft", "--color=always", "$left", "$right"]
pager = ["delta", "--pager", "less -FRX"]
diff-editor = ["nvim", "-c", "DiffEditor $left $right $output"]
conflict-marker-style = "git"

[[--scope]]
--when.commands = ["diff", "show"]
[--scope.ui]
pager = "delta"
